### ISSUE TITLE
No action is taking place on Edit Repositories in Updates Tab

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/gingerbase#113]
No action is taking place on Edit Repositories in Updates Tab

**Comment by danielhb** [comment]
Any errors being shown in the log or is it failing silently?

**Comment by archu-s** [comment]
failing silently

**Comment by pvital** [comment]
I can confirm that edit option is not working on Gingerbase 2.2.0 and on today's HEAD (188db29). After select an existent repository entry, the option to edit the repository is disabled. 

![screenshot from 2016-07-07 09-55-59](https://cloud.githubusercontent.com/assets/699330/16653889/8adaa6ee-4429-11e6-8c34-6308555c544d.png)

IMO, this is a regression issue since this feature worked in past releases.
