### ISSUE TITLE
On Reboot or shutdown from UI, the UI does not indicate if system got rebooted or not.

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/gingerbase#119]
From UI reboot or shutdown, brings wok down till system is not up.
However UI page just stay there and does not indicate user if system goes down or not.
And if user refreshed the page, then  only user got to know that wok is no more reachable.

showing message like  'rebooting system now you will be disconnected'  and refreshing the page will help user that system is unavailable

**Comment by pvital** [comment]
IMO, this is not an issue.

Both actions have a confirmation box, which already warn the user about the reboot or shutdown and proceeds only after user click on OK button, agreeing with the incoming connection failure. So showing a message like 'rebooting system now you will be disconnected' is totally unnecessary.

Now, about the page do not indicate the connection was lost, I think the problem is the missing of refresh on the page where the buttons are located. Wok (if I'm not wrong) already checks the connection and warn user if wokd (or the host) is off. You can check this on Guest page of Kimchi, and then shutting down wokd.service (or the host).

So, a patch would be great improving the refresh on the page where the buttons are.

**Comment by danielhb** [comment]
Just tested in a VM. This is the message when about to reboot:

![image](https://cloud.githubusercontent.com/assets/866780/16665921/afa422b6-445b-11e6-8637-f727788b1b08.png)

And this is the page after pressing OK:

![image](https://cloud.githubusercontent.com/assets/866780/16665956/e53b3e82-445b-11e6-836b-c20ef17fa2c3.png)

The message about virtual machine running is wrong. It hadn't any VM runnning and the reboot was successful. But note the first message. It indicates that the page lost connectivity, without needing to refresh it.

I'll test with your patch to see what changes, but I don't see much problems here

**Comment by danielhb** [comment]
This is the results with the v2 of the patch:

![image](https://cloud.githubusercontent.com/assets/866780/16668334/e4db986e-4466-11e6-9659-6a29bafde8e7.png)

The message 'there are virtual machines running' message that appeared before is gone, which is good. I don't mind the message saying about the shutdown/reboot, but we need to get rid of one of the messages that appeared next:

"Can not contact the host system. Verify the host system is up and that you have network connectivity to it. HTTP request response rejected."

and

"GGBHOST6002E: Unable to contact host system. Verify the host system is up and network connectivity is available."

Are redundant and say basically the same thing.

**Comment by alinefm** [comment]
Can we close this issue? Seems the patch was already applied upstream.

**Comment by atreyeemukhopadhyay** [comment]
Issue is fixed.
