### ISSUE TITLE
Do not make requests when repositories or software update section is collapsed

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/gingerbase#123]
Today when you do to "Updates" tab under Host tab, 2 requests are made to get the repositories information and the packages marked to be updated.

Those requests should only be done when user opens the section.

Originally reported on https://github.com/kimchi-project/kimchi/issues/381

**Comment by samhenri** [comment]
Before rendering the collapsible panel, the repositories widget calls gingerbase.listRepositories() API and then it builds the HTML.
In order to achieve this requirement we would have to make a change in wok.list() JS to create the HTML markup for the panel-group content only, instead of the whole panel group with headers and collapse icon and make these two elements static HTML markup on the host-update template and load the wok.list() with the gingerbase.listRepositories() result only once the user clicked the panel header. 

Now for the Software Updates panel, each time the user clicks the panel group, it wouldn't just call ginger.listSoftwareUpdates() but all the other functions that are necessary to build the jQuery Bootgrid table first and then list the software updates. The user may click on the panel group while an update is in progress and this would trigger "Package manager instance running in the system" error messages all the time.

**Comment by peterpennings** [comment]
@alinefm @danielhb any updates on this issue?

**Comment by danielhb** [comment]
@peterpennings I don't remember any UI patch fixing this issue, so it still happens

**Comment by samhenri** [comment]
@danielhb We are waiting a position based on my comment above because at this moment is almost impossible to fix this without making a big change on Wok and a datatable rework on Software Updates

**Comment by danielhb** [comment]
@samhenri if a major WoK change is needed, go for it. However let's be sure that we do not break stuff up in the process.

Also, we need to assess if this bug will keep making sense after the sidebar is implemented.

**Comment by samhenri** [comment]
Exactly. I don't think it makes sense to make this change now if we going for the sidebar design

**Comment by danielhb** [comment]
@samhenri let's focus on the sidebar then. We can close this bug when the sidebar is deployed

**Comment by samhenri** [comment]
Hi, @danielhb @alinefm I just realized that the sidebar design is being developed for Ginger and this issue is for Gingerbase. The comment that I made above is still valid, we would have to work on major changes on both panels.
