### ISSUE TITLE
Enable/Disable repository button does not work

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/gingerbase#143]
When an enabled repository is selected, button is not enabled and does not change to Disable.

**Comment by alinefm** [comment]
This issue is duplicated of #122 

What happens is a conflict with 2 bootgrid in the same tab: one for repositories and other one for updates.
When there is no packages to be updated, the updates bootgrid is loaded automatically and then, even though the updates section is closed, the conflict happens.

When there are some packages to be updated, the updates bootgrid takes some time to be built and in this time frame the repositories actions work as expected. Once the updates bootgrid is loaded, the conflict happens and the repositories actions stop working.

I will close this issue and keep tracking on it on #122.
