### ISSUE TITLE
Cannot build gingerbase out of wok structure

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/gingerbase#17]
Distro: Ubuntu 15.10 x86_64
Tried to clone gingerbase separately from wok and could not build it. The same problem occurs trying to build gingerbase in wok tree before building wok itself.

Compiling .scss file src/gingerbase.scss
sassc -s expanded src/gingerbase.scss gingerbase.css
sassc: error: Error: File to import not found or unreadable: ../../../../../../../ui/css/src/modules/wok-variables
       Parent style sheet: /home/dev/gingerbase/ui/css/src/gingerbase.scss
        on line 22 of src/gingerbase.scss

> > @import "../../../../../../../ui/css/src/modules/wok-variables";
> >    ^

Makefile:517: recipe for target 'gingerbase.css' failed
make[3]: **\* [gingerbase.css] Error 1
make[3]: Leaving directory '/home/dev/gingerbase/ui/css'
Makefile:373: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/home/dev/gingerbase/ui'
Makefile:604: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/dev/gingerbase'
Makefile:443: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by danielhb** [comment]
As I've said in #23, building the plug-ins individually was something that I would like but it's not practical.

We can reach the state where the plug-ins can be built standalone - I think we are in that state already. But we can't run the unit tests, for example, because they use WoK facilities to run. There's also the UI development process to be accounted for - the UI base classes are inside WoK too.

I believe we're better of simply putting in the docs (README) that to build Gingebase one would need WoK source code as well. #23 is already taking care of that, so I'll close this bug.

Thanks for reporting the issue, @lcorreia !
